config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'

  resources :posts do
    resource :likes, module: :posts
  end
  
  resources :users, :only => :show

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes

  def likes?(post)
   post.likes.where(user_id: id).any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end


private

  def set_post
    @post=Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(:user => current_user))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if current_user.admin?
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Must be admin to delete post.' }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category, :user_id)
    end

    attr_accessor :post
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @posts = Post.all
    @last = Post.last
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @posts = Post.all
  end

  def show
    @user = User.find(params[:id])
    @username = @user.email.split("@")[0] # OR @user.email[/[^@]+/]
    @all_likes = @user.likes.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts/likes_helper.rb
module Posts::LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="mainhead">
  <div class="row">
    <div class="nav-brand col-md-1 col-md-offset-1">
      <h1><%= link_to'Tester', root_path %></h1>
    </div>
    <div class="links col-md-4 col-md-offset-5"><br>
      <%= link_to 'new post', new_post_path %>
      <%= link_to 'view posts', posts_path %>

      <% if user_signed_in? %>
        <%= link_to "Welcome, #{current_user.email}", user_path(current_user) %>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <%= render :partial => "layouts/header" %>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@post) %>
  <%= link_to "Unlike", post_likes_path(@post), method: :delete, remote: true %>
<% else %>
  <%= link_to "Like", post_likes_path(@post), method: :post, remote: true %> <!-- allows JS response -->
<% end %>

<%= @post.likes.count %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class ="lastpost">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th>Likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.order('likes_count DESC').each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.category %></td>
        <td><%= post.likes_count %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user==post.user %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/likes/create.js.erb
$("#likes").html("<%=j render partial: "posts/likes" %>");

app/views/posts/likes/destroy.js.erb
$("#likes").html("<%=j render partial: "posts/likes" %>");

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category %>
</p>
<p>
  <strong>Author:</strong>
  <%= @post.user.email %>
</p>

<div id="likes">
    <%= render partial: "likes" %>
</div><br>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/index.html.erb
<div class="hero">
</div>
<br><br><br><!--
<h3>Title: <%= @last.title %> </h3> <h6>(<%= @last.category %>)</h6><br>
<h4>  <%= @last.content %> <br> </h5>-->

<% @posts.order('likes_count DESC').each do |post| %>
  <h3><%= link_to post.title, post_path(post) %><br></h3>
  <h4><%= post.category %><br></h4>
  <h4><%= post.content %></h4>
  <h4>Likes: <%= post.likes_count %></h4><br><br>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.email %><br></h3>
<h3><%= @username %><br></h3>
<h4>Total Likes: <%= @all_likes %></h4><br>

<% @user.posts.each do |post| %>
<h4><%= link_to post.title, post_path(post) %></h4>
    <h5>Likes: <%= post.likes.count %></h5>
<% end %>